name: boswaves

services:
  # directus:
  #   image: directus/directus:latest
  #   restart: always
  #   ports:
  #     - "8055:8055"
  #   environment:
  #     KEY: "replace-with-random-string"
  #     SECRET: "replace-with-random-string"

  #     # Database (PostgreSQL recommended)
  #     DB_CLIENT: "pg"
  #     DB_HOST: "postgres"
  #     DB_PORT: "5432"
  #     DB_DATABASE: "directus"
  #     DB_USER: "directus"
  #     DB_PASSWORD: "directus"

  #     # Admin user
  #     ADMIN_EMAIL: "admin@example.com"
  #     ADMIN_PASSWORD: "d1r3ctu5"

  #     # Public URL
  #     PUBLIC_URL: "https://cdn.yourdomain.com"

  #     # File storage
  #     STORAGE_LOCATIONS: "local"
  #     STORAGE_LOCAL_ROOT: "./uploads"

  #     # Image transformations
  #     ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION: "6000"

  #   volumes:
  #     - ./uploads:/directus/uploads
  #     - ./extensions:/directus/extensions
  #   depends_on:
  #     - postgres

  postgres:
    image: bw/postgres:latest
    container_name: bw-postgres
    build:
      context: ./services/postgres
      dockerfile: Dockerfile
    environment:
    - POSTGRES_DB=${PG_DATABASE}
    - POSTGRES_USER=${PG_USERNAME}
    - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
    - postgres_vol:/var/lib/postgresql/data
    networks:
    - postgres_net
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${PG_USERNAME} -d ${PG_DATABASE}'" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  pgadmin:
    image: dpage/pgadmin4
    container_name: bw-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
    - "5440:80"
    volumes:
    - pgadmin_vol:/var/lib/pgadmin
    networks:
    - host_net
    - postgres_net
    depends_on:
      postgres:
        condition: service_healthy

  web:
    image: bw/website:latest
    container_name: bw-web
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
    - PG_PORT=5432
    - PG_HOST=postgres
    - PG_USERNAME=${PG_USERNAME}
    - PG_PASSWORD=${PG_PASSWORD}
    - PG_DATABASE=${PG_DATABASE}
    networks:
    - host_net
    - postgres_net
    ports:
    - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres_vol:
    driver: local
  pgadmin_vol:
    driver: local
  # prometheus_vol:
  #   driver: local
  # grafana_vol:
  #   driver: local

networks:
  host_net:
    driver: bridge
  postgres_net:
    driver: bridge
    internal: true
