#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<EOF
-- role
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$DIRECTUS_USER') THEN
    CREATE ROLE $DIRECTUS_USER LOGIN PASSWORD '$DIRECTUS_PASSWORD';
  END IF;
END \$\$;
EOF

# create database if not exists
psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" -tc \
  "SELECT 1 FROM pg_database WHERE datname = '$DIRECTUS_DB'" | grep -q 1 || \
  psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE DATABASE $DIRECTUS_DB"

# grant permissions
psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$DIRECTUS_DB" <<EOF
GRANT CREATE ON SCHEMA public TO $DIRECTUS_USER;
GRANT USAGE ON SCHEMA public TO $DIRECTUS_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $DIRECTUS_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO $DIRECTUS_USER;
EOF