#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<EOF
-- role
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$STORE_USER') THEN
    CREATE ROLE $STORE_USER LOGIN PASSWORD '$STORE_PASSWORD';
  END IF;
END \$\$;
EOF

# create database if not exists
psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" -tc \
  "SELECT 1 FROM pg_database WHERE datname = '$STORE_DB'" | grep -q 1 || \
  psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE DATABASE $STORE_DB"

# grant permissions
psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$STORE_DB" <<EOF
GRANT ALL ON DATABASE $STORE_DB TO $STORE_USER;
GRANT CREATE ON SCHEMA public TO $STORE_USER;
GRANT USAGE ON SCHEMA public TO $STORE_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $STORE_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO $STORE_USER;
EOF