ALTER TYPE "public"."price_model" RENAME TO "pricing_model";--> statement-breakpoint
DROP VIEW "public"."cart_data";--> statement-breakpoint
DROP MATERIALIZED VIEW "public"."plan_data";--> statement-breakpoint
ALTER TABLE "item_price" RENAME TO "plan_price";--> statement-breakpoint
ALTER TABLE "plan_price" DROP CONSTRAINT "item_price_id_item_info_id_fk";
--> statement-breakpoint
ALTER TABLE "plan_price" DROP CONSTRAINT "item_price_uuid_pk";--> statement-breakpoint
ALTER TABLE "plan_price" ADD CONSTRAINT "plan_price_uuid_pk" PRIMARY KEY("uuid");--> statement-breakpoint
ALTER TABLE "plan_price" ADD CONSTRAINT "plan_price_id_item_info_id_fk" FOREIGN KEY ("id") REFERENCES "public"."item_info"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."charge_data" AS (select "item_info"."id", "item_info"."name", "item_info"."status", json_agg(json_build_object('id', "plan_price"."id", 'uuid', "plan_price"."uuid", 'price', "plan_price"."price", 'period_unit', "plan_price"."period_unit", 'pricing_model', "plan_price"."pricing_model", 'currency_code', "plan_price"."currency_code", 'created_at', "plan_price"."created_at", 'updated_at', "plan_price"."updated_at", 'archived_at', "plan_price"."archived_at")) as "prices", "item_info"."created_at", "item_info"."updated_at", "item_info"."archived_at" from "item_info" left join "plan_price" on "plan_price"."id" = "item_info"."id" where "item_info"."type" = 'charge' group by "item_info"."id");--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."plan_data" AS (select "item_info"."id", "item_info"."name", "item_info"."type", "item_info"."slug", "item_info"."status", json_build_object('id', "item_script"."id", 'uuid', "item_script"."uuid", 'type', "item_script"."type", 'image', "item_script"."image", 'description', "item_script"."description") as "script", json_agg(json_build_object('id', "plan_price"."id", 'uuid', "plan_price"."uuid", 'price', "plan_price"."price", 'period_unit', "plan_price"."period_unit", 'pricing_model', "plan_price"."pricing_model", 'currency_code', "plan_price"."currency_code", 'created_at', "plan_price"."created_at", 'updated_at', "plan_price"."updated_at", 'archived_at', "plan_price"."archived_at")) as "prices", "item_info"."created_at", "item_info"."updated_at", "item_info"."archived_at" from "item_info" left join "item_script" on "item_script"."id" = "item_info"."id" left join "plan_price" on "plan_price"."id" = "item_info"."id" where "item_info"."type" = 'plan' group by "item_info"."id", "item_script"."id");