services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
    - "5440:80"
    volumes:
    - pgadmin_vol:/var/lib/pgadmin
    networks:
    - shared_net
    - postgres_net
    depends_on:
      postgres:
        condition: service_healthy

  nats_nui:
    image: ghcr.io/nats-nui/nui:latest
    ports:
    - 31311:31311
    volumes:
    - nui_vol:/db
    networks:
    - shared_net
    - nats_net
    depends_on:
      nats:
        condition: service_healthy

  ngrok:
    image: ngrok/ngrok
    container_name: bw-ngrok
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTH}
    command:
    - "http"
    - http://host.docker.internal:3000
    - "--url=${NGROK_DNS}"
    networks:
    - shared_net
volumes:
  grafana_vol:
  pgadmin_vol:
  nui_vol:


