name: bw-smtp

include:
- ./postgres.yaml

services:
  directus:
    image: directus/directus:latest
    container_name: bw-directus
    restart: always
    ports:
    - 8055:8055
    environment:
      KEY: ${CDN_KEY}
      SECRET: ${CDN_SECRET}

      # Database (PostgreSQL recommended)
      DB_PORT: 5432
      DB_CLIENT: pg
      DB_HOST: postgres
      DB_USER: ${CDN_PG_USERNAME}
      DB_DATABASE: ${CDN_PG_DATABASE}
      DB_PASSWORD: ${CDN_PG_PASSWORD}

      # Public URL
      PUBLIC_URL: ${DIRECTUS_DNS}

      # Admin user
      ADMIN_EMAIL: ${CDN_ADMIN_USER}
      ADMIN_PASSWORD: ${CDN_ADMIN_PASSWORD}

      # Admin user
      CORS_ENABLED: ${CDN_CORS_ENABLED}
      CORS_ORIGIN: ${CDN_CORS_ORIGIN}

      # Admin user
      # CONTENT_SECURITY_POLICY_DIRECTIVES__ENABLED: false
      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: ${CDN_CSPD_FRAME}

      # File storage
      STORAGE_LOCATIONS: local
      STORAGE_LOCAL_ROOT: ./uploads

      # Image transformations
      ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION: 6000

    volumes:
    - directus_vol:/uploads:/directus/uploads
    - directus_vol:/extensions:/directus/extensions
    networks:
    - postgres_net
    - shared_net
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  directus_vol:
