// Generated by @boswaves-inc/codegen 

import { Codec, NatsConnection, RequestOptions, JetStreamClient, JSONCodec, connect } from "nats";
import type { Subject, ScheduleArgs, SendArgs } from "./routes";
import type { NatsConfig } from "./types";

export class Smtp {
  private _codec: Codec<unknown>;
  private _connection: NatsConnection;
  private _jetstream: JetStreamClient;

  private constructor(connection: NatsConnection, jetsream: JetStreamClient) {
    this._codec = JSONCodec();
    this._jetstream = jetsream;
    this._connection = connection;
  }

  private async _request<T>(topic: Subject, body: T, opts?: RequestOptions) {
    const payload = this._codec.encode(body);
    await this._connection.request(topic, payload, opts);
  }

  public async schedule(body: ScheduleArgs, opts?: RequestOptions) {
    return await this._request('smtp.schedule', body, opts);
  }

  public async send(body: SendArgs, opts?: RequestOptions) {
    return await this._request('smtp.send', body, opts);
  }

  public static async connect({ jetstream, ...args }: NatsConfig): Promise<Smtp> {
    const connection = await connect({ ...args });
    const stream = connection.jetstream(jetstream);
    return new Smtp(connection, stream);
  }

}

