// Generated by @boswaves-inc/codegen 

import { NatsConnection, RequestOptions, Payload, ConnectionOptions, connect as natsConnect, JetStreamOptions, JetStreamClient } from "nats";
import type { Subject, ScheduleArgs, SendArgs } from "./routes";

export class Smtp {
  private _connection: NatsConnection;
  private _jetstream: JetStreamClient;

  private constructor(connection: NatsConnection, jetsream: JetStreamClient) {
    this._connection = connection;
    this._jetstream = jetsream;
  }

  private async _request<T>(topic: Subject, body: T, opts?: RequestOptions) {
    await this._connection.request(topic, JSON.stringify(body), opts);
  }

  public async schedule(body: ScheduleArgs, opts?: RequestOptions) {
    return await this._request('smtp.schedule', body, opts);
  }

  public async send(body: SendArgs, opts?: RequestOptions) {
    return await this._request('smtp.send', body, opts);
  }

  public static async connect({ jetstream, ...args }: ConnectionOptions & { jetstream?: JetStreamOptions; }): Promise<Smtp> {
    const connection = await natsConnect(args);
    const stream = connection.jetstream(jetstream);
    return new Smtp(connection, stream);
  }

}

