import { Project, ts, type SourceFile } from "ts-morph";

export const write = async <T>(output: string, tx: (args: { file: SourceFile, project: Project }) => Promise<T>) => {
    const project = new Project();
    const file = project.createSourceFile(output, '', { overwrite: true, });

    const result = await tx({ file, project })

    file.formatText({
        indentSize: 2,
        convertTabsToSpaces: true,
        semicolons: ts.SemicolonPreference.Insert
    });

    // Normalize any existing double newlines first
    file.replaceWithText(file.getFullText().replace(/\n{2,}/g, '\n'));

    // Add blank lines between top-level declarations (excluding imports)
    const declarations = [
        ...file.getTypeAliases(),
        ...file.getInterfaces(),
        ...file.getClasses(),
        ...file.getFunctions(),
        ...file.getVariableStatements(),
    ].sort((a, b) => b.getStart() - a.getStart());

    for (const decl of declarations) {
        decl.appendWhitespace('\n');
    }

    // Add blank line after last import
    const imports = file.getImportDeclarations();
    if (imports.length > 0) {
        imports[imports.length - 1].appendWhitespace('\n');
    }

    // Add blank lines between class members (excluding properties)
    for (const cls of file.getClasses()) {
        const properties = cls.getProperties();
        const methods = [
            ...cls.getConstructors(),
            ...cls.getMethods(),
        ].sort((a, b) => b.getStart() - a.getStart());

        // Add blank line after last property (before constructor/methods)
        if (properties.length > 0) {
            properties[properties.length - 1].appendWhitespace('\n');
        }

        // Add blank lines between constructors and methods
        for (const member of methods) {
            member.appendWhitespace('\n');
        }
    }

    file.organizeImports()
    file.insertText(0, '// Generated by @boswaves-inc/codegen \n\n');

    await file.save();

    return result
}

export const edit = async <T>(input: string, tx: (args: { file: SourceFile, project: Project }) => Promise<T>) => {
    const project = new Project();
    const file = project.addSourceFileAtPath(input);

    const result = await tx({ file, project });

    await file.save();

    return result;
}