// Generated by @boswaves-inc/codegen 

import { Codec, JetStreamClient, JSONCodec, NatsConnection, RequestOptions } from "nats";
import type { Subject } from "./routes";

export class SvcClient<Sub extends string = Subject> {
  private _codec: Codec<unknown>;
  protected _connection: NatsConnection;
  protected _jetstream: JetStreamClient;

  protected constructor(connection: NatsConnection, jetsream: JetStreamClient) {
    this._codec = JSONCodec();
    this._jetstream = jetsream;
    this._connection = connection;
  }

  protected async _request<T>(topic: Sub, body: T, opts?: RequestOptions) {
    const payload = this._codec.encode(body);
    await this._connection.request(topic, payload, opts);
  }

}

