// Generated by @boswaves-inc/codegen 

import { connect, RequestOptions } from "nats";
import { SvcClient } from "./client";
import { AuthLoginArgs, AuthResetArgs, AuthSignupArgs, AuthVerifyArgs, UserCreateArgs, UserDeleteArgs, UserGetArgs, UserListArgs, UserSignupArgs, UserUpdateArgs } from "./routes";
import { SvcConfig } from "./types";

export class Account extends SvcClient {
  public get auth(): Account$Auth {
    return new Account$Auth(this._connection, this._jetstream);
  }
  public get user(): Account$User {
    return new Account$User(this._connection, this._jetstream);
  }
  public static async connect({ jetstream, ...args }: SvcConfig): Promise<Account> {
    const connection = await connect({ ...args });
    const stream = connection.jetstream(jetstream);
    return new Account(connection, stream);
  }

}

class Account$Auth extends SvcClient<`account.auth.${string}`> {
  public async login(body: AuthLoginArgs, opts?: RequestOptions) {
    return await this._request('account.auth.login', body, opts);
  }

  public async reset(body: AuthResetArgs, opts?: RequestOptions) {
    return await this._request('account.auth.reset', body, opts);
  }

  public async signup(body: AuthSignupArgs, opts?: RequestOptions) {
    return await this._request('account.auth.signup', body, opts);
  }

  public async verify(body: AuthVerifyArgs, opts?: RequestOptions) {
    return await this._request('account.auth.verify', body, opts);
  }

}

class Account$User extends SvcClient<`account.user.${string}`> {
  public async create(body: UserCreateArgs, opts?: RequestOptions) {
    return await this._request('account.user.create', body, opts);
  }

  public async delete(body: UserDeleteArgs, opts?: RequestOptions) {
    return await this._request('account.user.delete', body, opts);
  }

  public async get(body: UserGetArgs, opts?: RequestOptions) {
    return await this._request('account.user.get', body, opts);
  }

  public async list(body: UserListArgs, opts?: RequestOptions) {
    return await this._request('account.user.list', body, opts);
  }

  public async signup(body: UserSignupArgs, opts?: RequestOptions) {
    return await this._request('account.user.signup', body, opts);
  }

  public async update(body: UserUpdateArgs, opts?: RequestOptions) {
    return await this._request('account.user.update', body, opts);
  }

}

