// Generated by @boswaves-inc/codegen 

import { Codec, connect, JetStreamClient, JSONCodec, NatsConnection, RequestOptions } from "nats";
import type { AuthLoginArgs, AuthResetArgs, AuthSignupArgs, AuthVerifyArgs, Subject, UserCreateArgs, UserDeleteArgs, UserGetArgs, UserListArgs, UserSignupArgs, UserUpdateArgs } from "./routes";
import type { SvcConfig } from "./types";

export class Account {
  private _codec: Codec<unknown>;
  private _connection: NatsConnection;
  private _jetstream: JetStreamClient;

  private constructor(connection: NatsConnection, jetsream: JetStreamClient) {
    this._codec = JSONCodec();
    this._jetstream = jetsream;
    this._connection = connection;
  }

  private async _request<T>(topic: Subject, body: T, opts?: RequestOptions) {
    const payload = this._codec.encode(body);
    await this._connection.request(topic, payload, opts);
  }

  public async authLogin(body: AuthLoginArgs, opts?: RequestOptions) {
    return await this._request('account.auth.login', body, opts);
  }

  public async authReset(body: AuthResetArgs, opts?: RequestOptions) {
    return await this._request('account.auth.reset', body, opts);
  }

  public async authSignup(body: AuthSignupArgs, opts?: RequestOptions) {
    return await this._request('account.auth.signup', body, opts);
  }

  public async authVerify(body: AuthVerifyArgs, opts?: RequestOptions) {
    return await this._request('account.auth.verify', body, opts);
  }

  public async userCreate(body: UserCreateArgs, opts?: RequestOptions) {
    return await this._request('account.user.create', body, opts);
  }

  public async userDelete(body: UserDeleteArgs, opts?: RequestOptions) {
    return await this._request('account.user.delete', body, opts);
  }

  public async userGet(body: UserGetArgs, opts?: RequestOptions) {
    return await this._request('account.user.get', body, opts);
  }

  public async userList(body: UserListArgs, opts?: RequestOptions) {
    return await this._request('account.user.list', body, opts);
  }

  public async userSignup(body: UserSignupArgs, opts?: RequestOptions) {
    return await this._request('account.user.signup', body, opts);
  }

  public async userUpdate(body: UserUpdateArgs, opts?: RequestOptions) {
    return await this._request('account.user.update', body, opts);
  }

  public static async connect({ jetstream, ...args }: SvcConfig): Promise<Account> {
    const connection = await connect({ ...args });
    const stream = connection.jetstream(jetstream);
    return new Account(connection, stream);
  }

}

