// Generated by @boswaves-inc/codegen 

import { Codec, NatsConnection, RequestOptions, JetStreamClient, JSONCodec, connect } from "nats";
import type { Subject, TenantCreateArgs, TenantDeleteArgs, TenantEditArgs, TenantGetArgs, TenantListArgs, UserCreateArgs, UserDeleteArgs, UserEditArgs, UserGetArgs, UserListArgs } from "./routes";
import type { SvcConfig } from "./types";

export class Account {
  private _codec: Codec<unknown>;
  private _connection: NatsConnection;
  private _jetstream: JetStreamClient;

  private constructor(connection: NatsConnection, jetsream: JetStreamClient) {
    this._codec = JSONCodec();
    this._jetstream = jetsream;
    this._connection = connection;
  }

  private async _request<T>(topic: Subject, body: T, opts?: RequestOptions) {
    const payload = this._codec.encode(body);
    await this._connection.request(topic, payload, opts);
  }

  public async tenantCreate(body: TenantCreateArgs, opts?: RequestOptions) {
    return await this._request('account.tenant.create', body, opts);
  }

  public async tenantDelete(body: TenantDeleteArgs, opts?: RequestOptions) {
    return await this._request('account.tenant.delete', body, opts);
  }

  public async tenantEdit(body: TenantEditArgs, opts?: RequestOptions) {
    return await this._request('account.tenant.edit', body, opts);
  }

  public async tenantGet(body: TenantGetArgs, opts?: RequestOptions) {
    return await this._request('account.tenant.get', body, opts);
  }

  public async tenantList(body: TenantListArgs, opts?: RequestOptions) {
    return await this._request('account.tenant.list', body, opts);
  }

  public async userCreate(body: UserCreateArgs, opts?: RequestOptions) {
    return await this._request('account.user.create', body, opts);
  }

  public async userDelete(body: UserDeleteArgs, opts?: RequestOptions) {
    return await this._request('account.user.delete', body, opts);
  }

  public async userEdit(body: UserEditArgs, opts?: RequestOptions) {
    return await this._request('account.user.edit', body, opts);
  }

  public async userGet(body: UserGetArgs, opts?: RequestOptions) {
    return await this._request('account.user.get', body, opts);
  }

  public async userList(body: UserListArgs, opts?: RequestOptions) {
    return await this._request('account.user.list', body, opts);
  }

  public static async connect({ jetstream, ...args }: SvcConfig): Promise<Account> {
    const connection = await connect({ ...args });
    const stream = connection.jetstream(jetstream);
    return new Account(connection, stream);
  }

}

