// Generated by @boswaves-inc/codegen 

export type AuthLoginArgs = {
  email: string;
  last_name: string;
  first_name: string;
};

export type AuthResetArgs = {
  email: string;
  last_name: string;
  first_name: string;
};

export type AuthSignupArgs = {
  email: string;
  last_name: string;
  first_name: string;
};

export type AuthVerifyArgs = {
  email: string;
  last_name: string;
  first_name: string;
};

export type UserCreateArgs = {
  email: string;
  last_name: string;
  first_name: string;
};

export type UserDeleteArgs = {};

export type UserGetArgs = {};

export type UserListArgs = {};

export type UserSignupArgs = {};

export type UserUpdateArgs = {};

export type Subject = 'account.auth.login' | 'account.auth.reset' | 'account.auth.signup' | 'account.auth.verify' | 'account.user.create' | 'account.user.delete' | 'account.user.get' | 'account.user.list' | 'account.user.signup' | 'account.user.update';

