// Generated by @boswaves-inc/codegen 

export type TenantCreateArgs = {};

export type TenantDeleteArgs = {};

export type TenantEditArgs = {};

export type TenantGetArgs = {};

export type TenantListArgs = {};

export type UserCreateArgs = {
  email: string;
  last_name: string;
  first_name: string;
};

export type UserDeleteArgs = {};

export type UserEditArgs = {};

export type UserGetArgs = {};

export type UserListArgs = {};

export type Subject = 'account.tenant.create' | 'account.tenant.delete' | 'account.tenant.edit' | 'account.tenant.get' | 'account.tenant.list' | 'account.user.create' | 'account.user.delete' | 'account.user.edit' | 'account.user.get' | 'account.user.list';

