// Generated by @boswaves-inc/codegen 

export type ButtonProps = {
  href?: string | undefined;
  target?: ("_self" | "_blank" | "_parent" | "_top") | undefined;
  variant?: ("primary" | "secondary" | "outline") | undefined;
  content: (string | number | boolean | ButtonProps | HeadingProps | HtmlProps | LeadProps | MarkdownProps | SubHeadingProps | TextProps)[];
  type: "button";
};

export type HeadingProps = {
  size?: ("h1" | "h2" | "h3") | undefined;
  content: (string | number | boolean | ButtonProps | HeadingProps | HtmlProps | LeadProps | MarkdownProps | SubHeadingProps | TextProps)[];
  type: "heading";
};

export type LeadProps = {
  content: (string | number | boolean | ButtonProps | HeadingProps | HtmlProps | LeadProps | MarkdownProps | SubHeadingProps | TextProps)[];
  type: "lead";
};

export type SubHeadingProps = {
  content: (string | number | boolean | ButtonProps | HeadingProps | HtmlProps | LeadProps | MarkdownProps | SubHeadingProps | TextProps)[];
  type: "sub-heading";
};

export type TextProps = {
  size?: ("default" | "lg") | undefined;
  content: (string | number | boolean | ButtonProps | HeadingProps | HtmlProps | LeadProps | MarkdownProps | SubHeadingProps | TextProps)[];
  type: "text";
};

export type HtmlProps = {
  content: string[];
  type: "html";
};

export type MarkdownProps = {
  content: string[];
  type: "markdown";
};

