// Generated by @boswaves-inc/codegen 

export type ScheduleArgs = {
  subject: string;
  to_emails: string[];
  cc_emails: string[] | undefined;
  bcc_emails: string[] | undefined;
};

export type SendArgs = {
  subject: string;
  content: (Auxiliary_2 | Auxiliary_4 | {
    content: string[];
    type: "html";
  } | Auxiliary_8 | {
    content: string[];
    type: "markdown";
  } | Auxiliary_14 | Auxiliary_20)[];
  to_emails: string[];
  cc_emails: string[] | undefined;
  bcc_emails: string[] | undefined;
};

export type Subject = 'smtp.schedule' | 'smtp.send';

