// Generated by @boswaves-inc/codegen 

import type { ButtonProps, HeadingProps, HtmlProps, LeadProps, MarkdownProps, SubHeadingProps, TextProps } from "./elements";

export type ScheduleArgs = {
  subject: string;
  to_emails: string[];
  cc_emails: string[] | undefined;
  bcc_emails: string[] | undefined;
};

export type SendArgs = {
  subject: string;
  content: (ButtonProps | HeadingProps | HtmlProps | LeadProps | MarkdownProps | SubHeadingProps | TextProps)[];
  to_emails: string[];
  cc_emails: string[] | undefined;
  bcc_emails: string[] | undefined;
};

export type Topic = 'smtp.schedule' | 'smtp.send';

